### ISSUE TITLE
Option to Track Billable time vs Total time logged

### ISSUE THREAD

**Issue by jclendenan** [BirjuVachhani/target_mate#10]
As an independent consultant, in an effort to track my total time (and get to be with the family as well), I track both total time worked, and billable time.   As such some days I do a bunch of internal work, but I have a target for number of hours of billable time as well on a daily/weekly basis to hit my financial goals.

Having an option to display both would be super handy.

Love the App btw.

**Comment by BirjuVachhani** [comment]
@jclendenan 
Thank you for opening this issue. I was looking around and I couldn't find an option in Toggl Track to mark a time entry as either billable/non-billable. It seems like per project feature and I am on free plan so I couldn't explore it much.

If I understand this correctly, this is more like a filter for whether to consider for billable/non-billable/both time entries for your target calculation. I can add this option in settings to either track billable/non-billable/all time entries. 

However, if you wanna have different goals and target for billable and non-billable hours tracking, which is multiple tracking feature, its something that is not supported yet and it requires significant amount of work and changes to the existing app. I can't promise if this can be implemented in near future or if it is going to be ever implemented.

Let me know which one it is! If it is the former, I can maybe implement it in near future since it would just be a filter for current time tracking!

**Comment by JuliaMathias** [comment]
I was gonna ask for the same thing and I think just having a filter would already be super useful.

**Comment by BirjuVachhani** [comment]
Wonderful! Also, since I can't mark individual time entries as billable/non-billable since I am on free plan, can you confirm that it can be done(if you are a paid user of Toggl track) so I know I need to apply filter on time entries coz I have no way to know!

Thanks!
